// Shared list of team members
export const teamMembers = [
  { name: 'אדיר חזן', role: 'מפיק ראשי', icon: '🎭', color: '#10b981' },
  { name: 'עמית תירוש', role: 'במאי אירועים', icon: '🎪', color: '#f59e0b' },
  { name: 'אבי לוי', role: 'מנהל הפקה', icon: '🎬', color: '#dc2626' },
  { name: 'דני קרן', role: 'אמן בידור', icon: '🎨', color: '#a855f7' },
  { name: 'דודי אמסלם', role: 'מוזיקאי', icon: '🎵', color: '#22d3ee' },
  { name: 'ליאור טמיר', role: 'כוריאוגרף', icon: '💃', color: '#ec4899' },
  { name: 'מומי שושן', role: 'מעצב תחפושות', icon: '👗', color: '#8b5cf6' },
  { name: 'משה מרקו', role: 'טכנאי סאונד', icon: '🎧', color: '#14b8a6' },
  { name: 'נדב חורי', role: 'מנהל במה', icon: '🎯', color: '#f97316' },
  { name: 'עופר גלעדי', role: 'מאמן פעלולים', icon: '🤸‍♂️', color: '#84cc16' },
  { name: 'אורן בנבנישתי', role: 'מעצב תפאורה', icon: '🏰', color: '#6366f1' },
  { name: 'רם אלמוג', role: 'מנהל ייצור', icon: '⚙️', color: '#ef4444' },
  { name: 'רועי וגנר', role: 'צלם ראשי', icon: '📸', color: '#06b6d4' },
  { name: 'רון דיקסון', role: 'מוביל קבוצה', icon: '👥', color: '#84cc16' },
  { name: 'אורי פייגין', role: 'מאפר ראשי', icon: '🎨', color: '#f59e0b' },
  { name: 'סהר אביאני', role: 'מעצבת שיער', icon: '💇‍♀️', color: '#ec4899' },
  { name: 'ספי בר', role: 'רכז בטיחות', icon: '🛡️', color: '#10b981' },
  { name: 'שלום מולדבסקי', role: 'מנהל לוגיסטיקה', icon: '🚛', color: '#8b5cf6' },
  { name: 'שלום ספיר', role: 'מנהל קהל', icon: '🎤', color: '#f97316' },
  { name: 'שי זיידנברג', role: 'מתכנת פעילויות', icon: '🎯', color: '#22d3ee' },
  { name: 'שולי מייקלס', role: 'רכזת ילדים', icon: '🧸', color: '#a855f7' },
  { name: 'טל שקד', role: 'מעצב גרפי', icon: '🖼️', color: '#14b8a6' },
  { name: 'יוסי חכם', role: 'יועץ יצירתי', icon: '💡', color: '#84cc16' },
  { name: 'יוסי עוז־סיני', role: 'רכז התנדבות', icon: '🤝', color: '#ef4444' },
  { name: 'אייל בישרי', role: 'מנהל קשרי קהילה', icon: '🌟', color: '#06b6d4' },
  { name: 'רועי וולקן', role: 'מתאמן חדש', icon: '🌱', color: '#10b981' }
];
